// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8CMh4akrjV3wZKECgUwVzkEZz5eY5huE',
    appId: '1:403001267424:web:775da378ee21edfa2f6c85',
    messagingSenderId: '403001267424',
    projectId: 'easy-med-c3f69',
    authDomain: 'easy-med-c3f69.firebaseapp.com',
    storageBucket: 'easy-med-c3f69.firebasestorage.app',
    measurementId: 'G-FRXGB62C53',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmrGcdWBfyd0vDICPXWkgrUp-cZDd4NDo',
    appId: '1:403001267424:ios:b4c49c76f4ec28262f6c85',
    messagingSenderId: '403001267424',
    projectId: 'easy-med-c3f69',
    storageBucket: 'easy-med-c3f69.firebasestorage.app',
    iosClientId: '403001267424-bodkdudp5tnq568cmhin3pc6l768e3h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyMed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8CMh4akrjV3wZKECgUwVzkEZz5eY5huE',
    appId: '1:403001267424:web:2b2aedb43955a74e2f6c85',
    messagingSenderId: '403001267424',
    projectId: 'easy-med-c3f69',
    authDomain: 'easy-med-c3f69.firebaseapp.com',
    storageBucket: 'easy-med-c3f69.firebasestorage.app',
    measurementId: 'G-QD3Q3L2DBZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmrGcdWBfyd0vDICPXWkgrUp-cZDd4NDo',
    appId: '1:403001267424:ios:b4c49c76f4ec28262f6c85',
    messagingSenderId: '403001267424',
    projectId: 'easy-med-c3f69',
    storageBucket: 'easy-med-c3f69.firebasestorage.app',
    iosClientId: '403001267424-bodkdudp5tnq568cmhin3pc6l768e3h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyMed',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Uwfkna46w-gHCLb3o-jS9kmHtWLjlNg',
    appId: '1:403001267424:android:78b6c7057b18b7622f6c85',
    messagingSenderId: '403001267424',
    projectId: 'easy-med-c3f69',
    storageBucket: 'easy-med-c3f69.firebasestorage.app',
  );

}