# ios/Podfile

# Set minimum iOS version
platform :ios, '15.0'

use_frameworks!
use_modular_headers!

target 'Runner' do
  # This installs all Flutter plugins including cloud_firestore
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

# Ensure all pods use iOS 15
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
